# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "44:1f:87:b7:ec:b5:67:5f:22:61:fb:0a:22:ac:30:c6"
      - run:
          name: Deploy Over SSH
          # command: ssh ubuntu@18.177.65.239 "cd /var/www/html/youtachannel.com/wp-content/themes/cider_card;git pull;echo Finish;exit;"
          # command: ssh ubuntu@18.177.65.239 "cd /var/;touch test;echo Finish;exit;"
          command: ssh git@github.com

workflows:
  # Name the workflow "welcome"
  # welcome:
  #   # Run the welcome/run job in its own container
  #   jobs:
  #     - welcome/run
  ssh-and-pull:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

# version: 2
# jobs:
#   deploy:
#     machine:
#       enabled: true
#     steps:
#       - checkout
#       - add_ssh_keys:
#           fingerprints:
#             - "44:1f:87:b7:ec:b5:67:5f:22:61:fb:0a:22:ac:30:c6"
#       - run:
#           name: Deploy Over SSH
#           command: ssh ubuntu@18.177.65.239 "cd /var/www/html/youtachannel.com/wp-content/themes/cider_card;git pull;echo Finish;exit;"

# workflows:
#   version: 2
#   ssh-and-pull:
#     jobs:
#       - deploy:
#           filters:
#             branches:
#               only: master
